from tkinter import *      
root = Tk()
menu = Menu(root)
root.config(menu=menu)
filemenu = Menu(menu)
menu.add_cascade(label='File', menu=filemenu)
filemenu.add_command(label='New')
filemenu.add_command(label='Open...')
filemenu.add_command(label='Save')
filemenu.add_command(label='Save As')
filemenu.add_separator()
filemenu.add_command(label='Exit', command=root.quit)
helpmenu = Menu(menu)
menu.add_cascade(label='Help', menu=helpmenu)
helpmenu.add_command(label='About')
helpmenu.add_command(label='Contact')
Contactmenu = Menu(menu)
Contactmenu.add_command(Label='Noreplay@gmail.com')
menu.add_cascade(label='Contact', menu=Contactmenu)
mainloop()
